name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Or specify your desired Python version, e.g., '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install setuptools first to potentially fix distutils issues for tree-sitter
        pip install setuptools 
        pip install -r requirements.txt
        # pytest, httpx, and tree-sitter are now in requirements.txt

    - name: Build Tree-sitter languages
      run: |
        python -m graph_core.analyzer.treesitter_parser.build_languages

    - name: Run tests with coverage
      run: pytest -v --cov=graph_core --cov-report=html # Generate HTML coverage report in htmlcov/

    - name: Generate graph snapshot
      # Using our dedicated script for generating graph snapshots
      run: python generate_graph_snapshot.py --src-dir graph_core --output graph_snapshot.json

    - name: Run performance profiler
      run: python performance/profiler.py # Adjust if arguments or specific output handling is needed

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: analysis-artifacts
        path: |
          graph_snapshot.json
          htmlcov/
      if: always() # Upload even if previous steps fail

    - name: Upload graph snapshot artifact (Example)
      uses: actions/upload-artifact@v4
      with:
        name: graph-snapshot
        path: graph_snapshot.json # Assuming the profiler or another process generates this
      if: always() # Upload even if previous steps fail, might contain partial data or error info 